### ISSUE TITLE
Radio selection

### ISSUE THREAD

**Issue by Cam0987** [aarmono/crypto_transceiver_instructions#3]
So I'm using a one of the reccomend USB cables and one that is similar but with separate mic and audio so I can use a headset I already have. Without fail it will always try to make the headset the radio. If both USB devices were the same you could just swap the cables around and it wouldn't be a problem. A way to select which USB sound card you want to use for the radio would be really useful.

**Comment by aarmono** [comment]
I've done a lot of work recently on the codebase which actually makes this a solvable problem now.

I added a udev rule that statically assigns a unique device id to each of the 4 USB ports on the raspberry pi. Then in the configuration page there's an option to statically assign a particular port (lower left, lower right, upper left, upper right) to either the radio or headset interface. Once this is done, the system will always attempt to use that hardware interface for radio or headset operation.

This is an optional configuration step, and if you don't do it the system will behave as before using the first initialized device as the headset interface and the second initialized device as the radio interface.

Still a bit of testing to be done because this new method requires that the volume settings file be "upgraded", and I want to make sure that's solid (though if it doesn't work then you can always just re-adjust the volume settings after the static assignment is made, at which point they too are bound the the USB port). And udev sometimes omits a character when assigning the device id, so I'd like to try to understand that. But that aside it all works flawlessly even when 4 USB audio devices are attached.

**Comment by aarmono** [comment]
Added an "Assign Audio Device" configuration option in the config utility which binds a USB port to either the headset or radio device.
